### PR TITLE
Replacing lodash with lodash-es

### PR DESCRIPTION
**Pull request by castevinz**
This PR allows to load lodash-es needed functions instead of complete lodash library.

### CODE REVIEW

**Comment by castevinz** [comment]
Hi @adamkleingit,
What do you think about this PR ? lodash-es is "tree-shakeable" compared to lodash, even if full bundle size is bigger...
- https://bundlephobia.com/result?p=lodash@4.17.15
- https://bundlephobia.com/result?p=lodash-es@4.17.15

**Comment by KeithGillette** [comment]
We evaluated replacing `lodash` with `lodash-es` in our project, but based on the benchmarks in [this comparison](https://www.blazemeter.com/blog/the-correct-way-to-import-lodash-libraries-a-benchmark), instead just blacklisted top-level imports from `lodash`. We did not do our own comparison, but for projects using small numbers of `lodash` functions, that apparently produces the smallest bundle sizes.

**Comment by vcastelain** [comment]
Thanks @KeithGillette for this benckmarks explanation... You can consider my PR useless or deprecated. I'll update my application to use Lodash by importing specifics methods instead of using lodash-es. Regards.

**Comment by vcastelain** [comment]
And sorry, I'm connected with my professional account, but it's me... castevinz = vcastelain ;)

**Comment by tobiasengelhardt** [comment]
Thanks for the PR @castevinz 
Closing this because we did this during the restructuring of the project.

**Pull request closed without merging**
