### PR TITLE
Correct `TreeComponent.options` typing to allow `angularCompilerOptions.strictTemplates: true`

### PR DESCRIPTION
**Pull request by KeithGillette**
Bugfix: Typing correction addressing Issue #795.

### CODE REVIEW

**Comment by tobiasengelhardt** [comment]
Hi @KeithGillette, can you rebase your changes on the current master? We did a few changes to the file structure.

**Comment by KeithGillette** [comment]
PR rebased. Many thanks for taking over maintenance of this library @tobiasengelhardt!

**Comment by tobiasengelhardt** [comment]
This will hopefully be released with an angular 9 update this week.

**Comment by ListeK83** [comment]
Hi @tobiasengelhardt. Please let me know when its going to be releases ?

**Comment by tobiasengelhardt** [comment]
@ListeK83 this was released with v9.0.2. Please note that the package name changed from `angular-tree-component` to `@circlon/angular-tree-component`. This sadly requires a few path adjustments after the update.

**Pull request merged**
